export default {
  webmap: '3ed30b730e5c4c2eaf2915fa5d87f4d1',
  title: 'World Heritage Online Maps Platform',
  subtitle: '',
  logoUrl: '',
  logoLinkUrl: '',
  aboutLinkUrl: '',
  downloadLinkUrl: '',
  printServiceUrl: 'https://gis.forest-atlas.org/server/rest/services/print/ExportWebMap/GPServer/Export%20Web%20Map',
  maskServiceUrl: '',
  mapThemeIds: '',
  mapThemes: '',
  narrative: '',
  hideHeader: true,
  hideFooter: true,
  includeMyGFWLogin: false,
  navLinksInNewTab: false,
  customColorTheme: '#0077D4',
  language: 'en',
  useAlternativeLanguage: true,
  alternativeWebmap: '3ed30b730e5c4c2eaf2915fa5d87f4d1',
  alternativeLanguage: 'fr',
  alternativeLanguageTitle: 'UNESCO WHOMP',
  alternativeLanguageSubtitle: '',
  alternativeMapThemes: '',
  alternativeNarrative: '',
  alternativeWebmapMenuName: 'Additional Layers',
  initialExtent: {
    x: null,
    y: null,
    z: null,
  },
  includeDocumentsTab: false,
  iso: '',
  viirsFires: true,
  intactForests: true,
  primaryForests: true,
  forma: false,
  aboveGroundBiomass: true,
  landCover: true,
  mangroves: false,
  sadAlerts: false,
  gladAlerts: true,
  gfwIntegratedAlertLayer: true,
  recentImagery: true,
  carbonSequence: true,
  carbonEmissions: true,
  treeCoverHeight: true,
  treeCover: true,
  treeCoverGain: true,
  treeCoverLoss: true,
  tropicalTreeCover: true,
  treeMosaicLandscapes: true,
  forestCarbonGrossRemovals: true,
  forestCarbonGrossEmissions: true,
  forestCarbonNetFlux: true,
  umdLandCover: true,
  drySpells: true,
  airQuality: true,
  windSpeed: true,
  webmapMenuName: 'Custom Layers',
  sharinghost: 'https://www.arcgis.com',
  analyticsCode: '',
  includeCartoTemplateLayers: false,
  cartoUser: 'wri-01',
  cartoTemplateId: 'tpl_07c315f8_c13e_11e4_b457_0e8dde98a187',
  cartoApiKey: 'your key here',
  cartoGroupLabel: {
    en: 'Carto Layers',
    fr: 'Carto Layers',
  },
  disabledAnalysisModules: [], //'VIIRS_FIRES', 'GLAD_ALERTS', 'TC_LOSS', 'IFL', 'LCC'
  // layers added in Arcgis Online, map id layer with the group id
  webmapLayerGroupsMap: {
    '18c00fedef1-layer-22': 'GROUP_CLIMATE',
  },
  layerPanel: {
    GROUP_WEBMAP: {
      order: 0,
      label: {},
      layers: [],
    },
    GROUP_WORLD_HERITAGE: {
      order: 1,
      groupType: 'default',
      label: {
        en: 'World Heritage',
        fr: 'Patrimoine mondial',
      },
      layers: [],
    },
    GROUP_NEAR_REAL_TIME: {
      order: 2,
      groupType: 'default',
      label: {
        en: 'Near Real Time',
        fr: 'Temps quasi reel',
      },
      layers: [
        {
          id: 'TREE_COVER_LOSS',
          order: 1,
          type: 'remoteDataLayer',
          uuid: '2aed67b3-3643-40d3-9c1e-8af9afb5d9e2',
        },
        {
          id: 'GFW_INTEGRATED_ALERTS',
          order: 8,
          type: 'remoteDataLayer',
          uuid: 'bd58f25d-d3bb-4d59-9daa-cecddd27d9f4',
          groupId: 'GROUP_LCD',
        },
        {
          id: 'VIIRS_ACTIVE_FIRES',
          order: 7,
          type: 'remoteDataLayer',
          uuid: '6d316908-92c8-4f95-8598-f2a0c72786af',
        },
      ],
    },
    GROUP_PROTECTION_AND_MANAGEMENT: {
      order: 3,
      groupType: 'default',
      label: {
        en: 'Protection and Management',
        fr: 'Protection et gestion',
      },
      layers: [],
    },
    GROUP_NATURAL_VALUES: {
      order: 4,
      groupType: 'default',
      label: {
        en: 'Natural Values',
        fr: 'Valeurs naturelles',
      },
      layers: [],
    },
    GROUP_SOCIOECONOMIC: {
      order: 5,
      groupType: 'default',
      label: {
        en: 'Socioeconomic',
        fr: 'Socioéconomique',
      },
      layers: [],
    },
    GROUP_THREATS_AND_RISKS: {
      order: 6,
      groupType: 'default',
      label: {
        en: 'Threats and Risks',
        fr: 'Menaces et risques',
      },
      layers: [],
    },
    GROUP_CLIMATE: {
      groupType: 'default',
      order: 7,
      label: {
        en: 'Climate',
        fr: 'Climat',
        es: 'Clima',
        pt: 'Clima',
        id: 'Iklim',
        zh: '气候',
        ka: 'კლიმატი',
        hy: 'Կլիմա',
        az: 'İqlim',
        nl: 'Klimaat',
      },
      layers: [
        {
          id: 'CARBON_SEQ',
          order: 1,
          type: 'remoteDataLayer',
          uuid: 'e7208398-0acd-4f73-a824-c4fe1e356e0c',
        },
        {
          id: 'DRY_SPELLS',
          order: 3,
          type: 'remoteDataLayer',
          uuid: '41936f95-094b-4ad9-8b8a-70fc159bd0ba',
        },
        {
          id: 'AIR_QUALITY',
          order: 3,
          type: 'remoteDataLayer',
          uuid: '67d8aed9-8eb3-4396-99a4-f0eee7295226',
        },
        {
          id: 'WIND_SPEED',
          order: 4,
          type: 'remoteDataLayer',
          uuid: '9fa60bd9-0643-4d0a-a569-0036e902d1f9',
        },
        {
          id: 'FOREST_CARBON_GROSS_REMOVALS',
          order: 6,
          type: 'remoteDataLayer',
          uuid: '79010c83-e62e-4744-96ed-130736daa651', // layer id
        },
        {
          id: 'FOREST_CARBON_GROSS_EMISSIONS',
          order: 7,
          type: 'remoteDataLayer',
          uuid: '0b45cb69-6432-449f-af38-25cdcda85d55',
        },
        {
          id: 'FOREST_CARBON_NET_FLUX',
          order: 8,
          type: 'remoteDataLayer',
          uuid: 'bd768c4b-f5f8-47f9-b6a0-5bb6078f0fac',
        },
        {
          id: 'CUSTOM_1',
          groupId: 'GROUP_CLIMATE',
          order: 10,
          type: 'flagship',
          origin: 'gfw-api',
          layerType: 'base-tile-layer',
          uuid: '1a08810f-34a4-4c53-8a37-6782d0ab6dec',
          label: {
            en: 'Custom 1',
          },
          sublabel: {
            en: 'Lorem ipsum',
          },
        },
        {
          id: 'AIR_QUALITY_CUSTOM',
          groupId: 'GROUP_CLIMATE',
          order: 9,
          type: 'flagship',
          // "datasetURL": "https://data-api.globalforestwatch.org/dataset/nexgddp_change_dry_spells_2000_2080/latest",
          // "datasetLegendConfigURL": "https://api.resourcewatch.org/v1/layer/7c497efb-1671-49bf-87a2-3c96ddb9ff88?filterIncludesByEnv=true&includes=vocabulary,metadata&env=production",
          // datasetURL: 'https://api.resourcewatch.org/v1/dataset/c66d7f3a-d1a8-488f-af8b-302b0f2c3840',
          // datasetLegendConfigURL: 'https://api.resourcewatch.org/v1/layer/70e900f1-2c37-470d-9367-7b34567e3084',
          origin: 'gfw-api',
          layerType: 'base-tile-layer',
          uuid: '70e900f1-2c37-470d-9367-7b34567e3084',
          label: {
            en: 'Air Quality testing',
            fr: 'Air Quality testing',
          },
          sublabel: {
            en: '2019, 30m, global, UMD/NASA GEDI',
            fr: '2019, 30m, global, UMD/NASA GEDI',
          },
        },
      ],
    },
    GROUP_LCD: {
      groupType: 'default',
      order: 8,
      label: {
        en: 'Land Cover Dynamics',
        fr: 'Evolution de la couverture des sols',
        es: 'Dinámica de la Cobertura del Suelo',
        pt: 'Dinâmica de cobertura da terra ',
        id: 'Land Cover Dynamics',
        zh: '土地覆盖动态数据',
        ka: 'მიწის საფარის დინამიკა',
      },
      layers: [
        {
          id: 'TREE_COVER_LOSS',
          order: 1,
          type: 'remoteDataLayer',
          uuid: '2aed67b3-3643-40d3-9c1e-8af9afb5d9e2',
        },
        {
          id: 'TREE_COVER_GAIN',
          order: 2,
          type: 'remoteDataLayer',
          uuid: 'cb016f17-f12d-463a-9dc2-aabcf5db566c',
        },
        {
          id: 'IMAZON_SAD',
          order: 3,
          type: 'remoteDataLayer',
          uuid: '3e9e86ae-e38d-4c59-8484-c8214ca5186a',
        },
        {
          id: 'FORMA_ALERTS',
          order: 4,
          type: 'remoteDataLayer',
          uuid: '56aa7e57-0ac4-446c-a82d-7713904b17c3',
        },
        {
          id: 'GLAD_ALERTS',
          order: 5,
          type: 'remoteDataLayer',
          uuid: '356f862b-3e70-493a-997b-dc2a193410e9',
        },
        {
          id: 'TERRA_I_ALERTS',
          order: 6,
          type: 'remoteDataLayer',
          uuid: '1fc7b0c5-259a-4685-8665-b2f1ed3f808f',
        },
        {
          id: 'VIIRS_ACTIVE_FIRES',
          order: 7,
          type: 'remoteDataLayer',
          uuid: '6d316908-92c8-4f95-8598-f2a0c72786af',
        },
        {
          id: 'GFW_INTEGRATED_ALERTS',
          order: 8,
          type: 'remoteDataLayer',
          uuid: 'bd58f25d-d3bb-4d59-9daa-cecddd27d9f4',
          groupId: 'GROUP_LCD',
        },
        {
          id: 'GLAD_S2_ALERTS',
          order: 9,
          type: 'remoteDataLayer',
          uuid: '3b869953-48c4-48d0-8023-5c64a311f3dd',
          groupId: 'GROUP_LCD',
        },
        {
          id: 'RADD_ALERTS',
          order: 10,
          type: 'remoteDataLayer',
          uuid: '440e53d0-36b3-47ad-993a-1c2018c3942c',
          groupId: 'GROUP_LCD',
        },
      ],
    },
    GROUP_LC: {
      groupType: 'default',
      order: 9,
      label: {
        en: 'Land Cover',
        fr: 'Couverture des sols',
        es: 'Cobertura terrestre',
        pt: 'Cobertura do Solo',
        id: 'Land Cover',
        zh: '土地覆盖',
        ka: 'მიწის საფარი',
      },
      layers: [
        {
          id: 'IFL',
          order: 1,
          type: 'remoteDataLayer',
          uuid: '5f815a7d-457e-4eae-a8e5-8864a60696ad',
        },
        {
          id: 'PRIMARY_FORESTS',
          order: 2,
          type: 'remoteDataLayer',
          uuid: 'edffb745-e523-462d-ad1e-3052006a3dbc',
        },
        {
          id: 'AG_BIOMASS',
          order: 3,
          type: 'remoteDataLayer',
          uuid: '04526d47-f3f5-4f76-a939-e5f7861fd085',
        },
        {
          id: 'TREE_COVER',
          order: 4,
          type: 'remoteDataLayer',
          uuid: '2569adca-ef87-42c4-a153-57c5e8ba0ef7',
        },
        {
          id: 'LAND_COVER',
          order: 5,
          type: 'remoteDataLayer',
          uuid: 'b8d3f175-0565-443f-839a-49eb890a4b3d',
        },
        {
          id: 'UMD_LAND_COVER',
          order: 6,
          type: 'remoteDataLayer',
          uuid: 'f22e0529-d398-4ccc-b943-e62d420fea89',
        },
        {
          id: 'TREE_COVER_HEIGHT',
          order: 7,
          type: 'remoteDataLayer',
          uuid: '2a83effa-f8be-425b-9766-502e65525861',
        },
        {
          id: 'TREES_MOSAIC_LANDSCAPES',
          order: 8,
          type: 'remoteDataLayer',
          uuid: '9e0c1e1e-a0a3-457f-a373-4104820f7a50',
        },
        {
          id: 'TROPICAL_TREE_COVER',
          order: 9,
          type: 'remoteDataLayer',
          uuid: 'b9183eca-84ed-48ed-83d5-a146a6e2a079',
        },
      ],
    },
    GROUP_IMAGERY: {
      groupType: 'imagery',
      order: 10,
      label: {
        en: 'Recent Imagery',
        fr: 'Recent Imagery',
        es: 'Recent Imagery',
        pt: 'Recent Imagery',
        id: 'Recent Imagery',
        zh: 'Recent Imagery',
        ka: 'Recent Imagery',
      },
      layers: [
        {
          order: 1,
          id: 'RECENT_IMAGERY',
          type: 'imagery',
          technicalName: 'recent_satellite_imagery',
          visible: false,
          label: {
            en: 'Recent Imagery',
            fr: 'Recent Imagery',
            es: 'Recent Imagery',
            pt: 'Recent Imagery',
            id: 'Recent Imagery',
            zh: 'Recent Imagery',
            ka: 'Recent Imagery',
          },
          dynamicSublabel: {
            en: '({DATE_TIME}, {CLOUD_COVERAGE}% cloud coverage, {INSTRUMENT})',
            fr: '({DATE_TIME}, {CLOUD_COVERAGE}% cloud coverage, {INSTRUMENT})',
            es: '({DATE_TIME}, {CLOUD_COVERAGE}% cloud coverage, {INSTRUMENT})',
            pt: '({DATE_TIME}, {CLOUD_COVERAGE}% cloud coverage, {INSTRUMENT})',
            id: '({DATE_TIME}, {CLOUD_COVERAGE}% cloud coverage, {INSTRUMENT})',
            zh: '({DATE_TIME}, {CLOUD_COVERAGE}% cloud coverage, {INSTRUMENT})',
            ka: '({DATE_TIME}, {CLOUD_COVERAGE}% cloud coverage, {INSTRUMENT})',
          },
        },
      ],
    },
    GROUP_BASEMAP: {
      groupType: 'basemap',
      order: 200,
      label: {
        en: 'Basemap',
        fr: 'Basemap',
        es: 'Basemap',
        pt: 'Basemap',
        id: 'Basemap',
        zh: 'Basemap',
        ka: 'საბაზო რუკა',
      },
      layers: [
        {
          id: 'wri_mono',
          thumbnailUrl: 'https://my.gfw-mapbuilder.org/img/wri_mono.png',
          title: {
            en: 'WRI Mono',
            fr: 'WRI Mono',
            es: 'WRI Mono',
            pt: 'WRI Mono',
            id: 'WRI Mono',
            zh: 'WRI Mono',
            ka: 'WRI Mono',
          },
        },
        {
          id: 'wri_contextual',
          thumbnailUrl: 'https://my.gfw-mapbuilder.org/img/wri_contextual.png',
          title: {
            en: 'WRI Contextual',
            fr: 'WRI Contextual',
            es: 'WRI Contextual',
            pt: 'WRI Contextual',
            id: 'WRI Contextual',
            zh: 'WRI Contextual',
            ka: 'WRI Contextual',
          },
        },
      ],
    },
    extraLayers: [
      {
        id: 'MASK',
        type: 'dynamic',
        order: 10000,
        url: 'https://gis.forest-atlas.org/server/rest/services/country_masks/country_mask_global/MapServer',
        opacity: 0.35,
        layerIds: [0],
      },
      {
        id: 'LEGEND_LAYER',
        type: 'dynamic',
        url: 'https://gis-gfw.wri.org/arcgis/rest/services/legends/MapServer',
        visible: false,
        opacity: 0,
        layerIds: [],
      },
      {
        id: 'USER_FEATURES',
        type: 'graphic',
        visible: true,
      },
    ],
  },
};
